name: Trivy

on:
  push:
    branches: [ master, development ]

  pull_request:
    branches: [ master, development ]

  schedule:
    - cron: '50 20 * * 0'

jobs:
  analyse:
    name: Analyse Docker image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build image from Dockerfile
        run: |
          docker build -t docker.io/nhsd/buying-catalogue/order-form:${{ github.sha }} .

      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: 'docker.io/nhsd/buying-catalogue/order-form:${{ github.sha }}'
          format: 'template'
          template: '@/contrib/sarif.tpl'
          output: 'trivy-results.sarif'
          severity: 'CRITICAL,HIGH'

      - name: Upload Trivy scan results to GitHub Security tab
        uses: github/codeql-action/upload-sarif@v1
        with:
          sarif_file: 'trivy-results.sarif'
